build: fold parameter-pack array

array: array.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++20

fold: fold.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++20

parameter-pack: parameter-pack.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++20
