build: print fold parameter-pack array

print: print.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++23

array: array.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++23

fold: fold.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++23

parameter-pack: parameter-pack.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++23
