build: hello-world events

hello-world: hello-world.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++20 -lsfml-graphics -lsfml-window -lsfml-system

events: events.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++20 -lsfml-graphics -lsfml-window -lsfml-system
