build: hello-world events game-of-life

hello-world: hello-world.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++20 -lsfml-graphics -lsfml-window -lsfml-system

events: events.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++20 -lsfml-graphics -lsfml-window -lsfml-system

game-of-life: game-of-life.cpp
	g++ -g $< -o $@ -Wall -Wextra -std=c++20 -lsfml-graphics -lsfml-window -lsfml-system
