#!/usr/bin/env python3

import turtle

turtle.up()
turtle.right(180)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.down()

color = int(1)

for x in range(50):
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(1)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(1)
    turtle.left(90)
