#!/usr/bin/perl -w
#	-*- Perl -*-		test:	
#
#	(usage)% test
#
#	Inputs:		
#			
#	Outputs:		
#
#	Kentaro Wuertele	Sat Aug 17 10:35:09 2019	Steal This Program!!!

use strict;

my %index_of_letter = (
    a => 0,
    b => 1,
    c => 2,
    d => 3,
    e => 4,
    f => 5,
    g => 6,
    h => 7,
    i => 8,
    j => 9,
    k => 10,
    l => 11,
    m => 12,
    n => 13,
    o => 14,
    p => 15,
    q => 16,
    r => 17,
    s => 18,
    t => 19,
    u => 20,
    v => 21,
    w => 22,
    x => 23,
    y => 24,
    z => 25,
    );

my %letter_of_index = (
     0 => 'a',
     1 => 'b',
     2 => 'c',
     3 => 'd',
     4 => 'e',
     5 => 'f',
     6 => 'g',
     7 => 'h',
     8 => 'i',
     9 => 'j',
     10 => 'k',
     11 => 'l',
     12 => 'm',
     13 => 'n',
     14 => 'o',
     15 => 'p',
     16 => 'q',
     17 => 'r',
     18 => 's',
     19 => 't',
     20 => 'u',
     21 => 'v',
     22 => 'w',
     23 => 'x',
     24 => 'y',
     25 => 'z',
    );


my $thing = lc shift;
print "$thing\n";

sub encode {
    my $letter = shift;
    my $offset = (int (rand (40)));
    my $direction = (int (rand(2)));
    my $index = $index_of_letter{$letter};
    if ($direction == 0) {
	$index = $index - $offset;
    } else {
	$index = $index + $offset;
    }
    my $wrapped_index = $index % 26;
    my $newletter = $letter_of_index{$wrapped_index};
    return "`$offset $direction $newletter`";
}

foreach my $letter (split (//, $thing)) {
    print (encode ($letter), " ");
}
print "\n";
