#!/usr/bin/perl

use strict;

my $thing = shift;

my $counter = 10;
my $counter_counter = 10;

if ($thing eq "exit") {
    print "exitting\n";
} elsif ($thing eq "stop") {
    print "stopping\n";
} else {
    print "not exitting or stopping\n";
}

while ($counter == 10) {
    print "$counter is 10\n";
    if ($counter_counter == 0) {
	$counter = 0;
    }
    $counter_counter -= 1;
}
print "$counter\n";

print "\n";

foreach my $counter(1 ... 20) {
    print "$counter\n";
}
