#!/usr/bin/perl

use strict;

my @layer_neurons = (3, 3, 2);

my @layer = ({input  => [],
	      bias   => [1, 1, 1],
	      weight => []},
	     {input  => [],
	      bias   => [1, 1, 1],
	      weight => []},
	     {input  => [],
	      bias   => [1, 1],
	      weight => []});

my @weights = ([[1, 1, 1],
		[1, 1, 1],
		[1, 1, 1]],
	       [[1, 1],
		[1, 1],
		[1, 1]]);
		   

my @layer_1_2_weights = ([1, 1, 1], [1, 1, 1], [1, 1, 1]);
my @layer_2_3_weights = ([1, 1], [1, 1], [1, 1]);

foreach my $neuron_id (0 .. $layer_neurons[0] - 1) {
    $layer[0]{input}[$neuron_id] = shift;
}

add_bias(0);

#multiply_weight(1);

foreach my $l2_id (0 .. $layer_neurons[1] - 1) {
    foreach my $l1_id (0 .. $layer_neurons[0] - 1) {
	$layer[1]{input}[$l2_id] += $layer[0]{output}[$l1_id] * $weights[0][$l1_id][$l2_id];
    }
    print "\$layer[1]{input}[$l2_id] = $layer[1]{input}[$l2_id]\n";
}

add_bias(1);

#multiply_weight(2);

foreach my $l3_id (0 .. $layer_neurons[2] - 1) {
    foreach my $l2_id (0 .. $layer_neurons[1] - 1) {
	$layer[2]{input}[$l3_id] += $layer[1]{output}[$l2_id] * $weights[1][$l2_id][$l3_id];
    }
    print "\$layer[2]{input}[$l3_id] = $layer[2]{input}[$l3_id]\n";
}

add_bias(2);

sub multiply_weight {
    my $layer_id = shift;
    foreach my $current_layer_neuron_id (0 .. $layer_neurons[$layer_id] - 1) {
	foreach my $old_layer_neuron_id (0 .. $layer_neurons[$layer_id - 1] - 1) {
	    $layer[$layer_id]{input}[$current_layer_neuron_id] += $layer[$layer_id - 1]{output}[$old_layer_neuron_id] * $weights[$layer_id][$old_layer_neuron_id][$current_layer_neuron_id];
	    print "\$layer[$layer_id]{input}[$current_layer_neuron_id], $layer[$layer_id]{input}[$current_layer_neuron_id] += \$layer[$layer_id - 1]{output}[$old_layer_neuron_id], $layer[$layer_id - 1]{output}[$old_layer_neuron_id] * \$weights[$layer_id][$old_layer_neuron_id][$current_layer_neuron_id], $weights[$layer_id][$old_layer_neuron_id][$current_layer_neuron_id]\n";
	}
	print "\$layer[$layer_id]{input}[$current_layer_neuron_id] = $layer[$layer_id]{input}[$current_layer_neuron_id]\n";
    }
}

sub add_bias {
    my $layer_id = shift;
    foreach my $neuron_id (0 .. $layer_neurons[$layer_id] - 1) {
	$layer[$layer_id]{output}[$neuron_id] = $layer[$layer_id]{input}[$neuron_id] + $layer[$layer_id]{bias}[$neuron_id];
	$layer[$layer_id]{output}[$neuron_id] = int($layer[$layer_id]{output}[$neuron_id]);
	print "\$layer[$layer_id]{output}[$neuron_id] = $layer[$layer_id]{output}[$neuron_id]\n";
    }
}

sub activation_function {
    my $weighted_input = shift;
    $weighted_input = 1/(1 + 3^-$weighted_input);
#    $weighted_input *= 1000;
    $weighted_input = int($weighted_input);
#    $weighted_input /= 1000;
}
