#!/usr/bin/perl -w
#	-*- Perl -*-		strings-and-numbers:	
#
#	(usage)% strings-and-numbers
#
#	Inputs:		
#			
#	Outputs:		
#
#	Kentaro Wuertele	Sat Jun  6 16:19:32 2020	3.141592653589793238462643383279502

use strict;

my $a = 3;
print $a , "\n";

my $b = $a + 4;
print $b , "\n";

$a = $a + 3;
print $a , "\n";

$b = $a . $b;
print $b , "\n";
